In [23]:
import numpy as np
import pandas as pd
print(f'Pandas version: {np.__version__}')

Pandas version: 2.2.6


# Nd-array
- Can only store the same data types

In [39]:
array = np.array([1,2,3,4,5,6,7,8])
print(array)

[1 2 3 4 5 6 7 8]


## Slicing & Indexing
- You can use indeces to access elements
- You can slice the array

In [25]:
print(array[2])
print(array[3:5])
print(array[-3::-1])
print(array.shape)


3
[4 5]
[76  6  5  4  3  2  1]
(9,)


In [36]:
# 2d array
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr_2d, arr_2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [27]:
# 2d array indexing & slicing
print(arr_2d)

print(f'Second element of the first array: {arr_2d[0][1]}')
print(f'The last element of the last array: {arr_2d[-1][-1]}')

# slicing fromat: arr[a:b, c:d] for arrays from (a) to (b-1), elements from 
print(f'Slicing from the second array to the last array: {arr_2d[0:4]}')
print(f'Slicing from the second array to the last array, third elements: {arr_2d[0:4, 2]}')
print(f'Slicing from the second array to the last array, elements of 1-2: {arr_2d[0:4, 0:2]}')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Second element of the first array: 2
The last element of the last array: 12
Slicing from the second array to the last array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Slicing from the second array to the last array, third elements: [ 3  6  9 12]
Slicing from the second array to the last array, elements of 1-2: [[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [46]:
# array reshaping
arr_test = array.reshape(-1, 4)
print(arr_test)
print()

arr_2d = arr_2d.reshape(-1)
print(arr_2d)
print()
arr_3d = arr_2d.reshape(2,2,3)
print(arr_3d)
print()
arr_3d = arr_2d.reshape(2,2,-1)     # You can also leave a missing part as -1 which numpy takes care of automatically
print(arr_3d)
print()
arr_3d = arr_2d.reshape(2,-1,3)     # You can also leave a missing part as -1 which numpy takes care of automatically
print(arr_3d)

[[1 2 3 4]
 [5 6 7 8]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
# Manually assigning the type of data
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print(float_array, float_array.dtype)
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype='float16')
print(float_array, float_array.dtype)

[1.1 2.2 3.3 4.4 5.5] float64
[1.1 2.2 3.3 4.4 5.5] float16


In [30]:
zero = np.zeros(12, dtype='int16')
print(zero, zero.dtype)
ones = np.ones(15, dtype='float64')
print(ones, ones.dtype)
tens = np.full((2, 5), 10)
print(tens, tens.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0] int16
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64
[[10 10 10 10 10]
 [10 10 10 10 10]] int64


In [31]:
# np.range()

nine = np.arange(1, 10)
print(nine)

even = np.arange(2, 13, 2)
print(even)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12]


In [32]:
# Arrays of "string"
# The default type of data type of string is Unicode

arr = np.array(['Korea', 'United Kingdom', 'United States'])
print(arr, arr.dtype)
arr = np.array(['Korea', 'United Kingdom', 'United States'], dtype='S')
print(arr, arr.dtype)

['Korea' 'United Kingdom' 'United States'] <U14
[b'Korea' b'United Kingdom' b'United States'] |S14


In [33]:
# Frequently used properties

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.nbytes)

(3,)
1
3
42


In [34]:
# Filtering in arrays

cond = nine > 4
print(cond)

greater_than_four = nine[cond]
print(greater_than_four)

cond = (nine > 1) & (nine < 6)
print(nine[cond])

# nan(Not a Number) only works with floats
# nine[cond] = np.nan
print(nine)

[False False False False  True  True  True  True  True]
[5 6 7 8 9]
[2 3 4 5]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# Array broadcasting

arr = np.array([1,2,3,4,5])
arr_2d = np.array([[10,20,30,40,50], [60,70,80,90,100], [-1,-2,-3,-4,-5]])
print(arr + 3)
print()
print(arr_2d * -1)
print()
print(arr_2d // arr)

[4 5 6 7 8]

[[ -10  -20  -30  -40  -50]
 [ -60  -70  -80  -90 -100]
 [   1    2    3    4    5]]

[[10 10 10 10 10]
 [60 35 26 22 20]
 [-1 -1 -1 -1 -1]]


In [50]:
arr = np.arange(1, 61)
arr_3d = arr.reshape(3,4,5)
print(arr_3d)
print()

arr_1d = np.arange(1, 6)
print(arr_3d // arr_1d)
print()

arr_2d = np.arange(1, 21).reshape(4, -1)
print(arr_3d // arr_2d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

[[[ 1  1  1  1  1]
  [ 6  3  2  2  2]
  [11  6  4  3  3]
  [16  8  6  4  4]]

 [[21 11  7  6  5]
  [26 13  9  7  6]
  [31 16 11  8  7]
  [36 18 12  9  8]]

 [[41 21 14 11  9]
  [46 23 16 12 10]
  [51 26 17 13 11]
  [56 28 19 14 12]]]

[[[ 1  1  1  1  1]
  [ 1  1  1  1  1]
  [ 1  1  1  1  1]
  [ 1  1  1  1  1]]

 [[21 11  7  6  5]
  [ 4  3  3  3  3]
  [ 2  2  2  2  2]
  [ 2  2  2  2  2]]

 [[41 21 14 11  9]
  [ 7  6  6  5  5]
  [ 4  4  4  3  3]
  [ 3  3  3  3  3]]]
